CREATE DATABASE netdisk;
USE netdisk;

CREATE TABLE user (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(20) NOT NULL
);

CREATE TABLE file (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL UNIQUE,
format VARCHAR(10),
path VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE relation (
uid INT UNSIGNED,
fid BIGINT UNSIGNED,
CONSTRAINT uf_pk PRIMARY KEY(uid, fid),
CONSTRAINT u_fk FOREIGN KEY(uid) REFERENCES user(id),
CONSTRAINT f_fk FOREIGN KEY(fid) REFERENCES file(id)
);